---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
    annotations:
        github.com/project-slug: ${{ values.githubOrgId.name | dump }}/${{ values.name | dump }}
    description: ${{ values.name | dump }}
    links:
        - icon: github
          title: Repository
          url: https://github.com/${{ values.githubOrgId.name | dump }}/${{ values.name | dump }}
    name: ${{ values.name | dump }}
spec:
    owner: user:guest
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    annotations:
        github.com/project-slug: ${{ values.githubOrgId.name | dump }}/${{ values.name | dump }}
        humanitec.com/orgId: ${{ values.orgId | dump }}
        humanitec.com/appId: ${{ values.name | dump }}
    description: node-workload
    links:
        - icon: github
          title: Repository
          url: https://github.com/${{ values.githubOrgId.name | dump }}/${{ values.name | dump }}
    name: ${{ values.name | dump }}-node-workload
    tags:
        - website
        - ui
        - golang
    title: node-workload
spec:
    dependsOn:
        - resource:${{ values.name | dump }}-node-workload-dns
        - resource:${{ values.name | dump }}-node-workload-postgres
    lifecycle: experimental
    owner: user:guest
    system: ${{ values.name | dump }}
    type: website
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
    description: ${{ values.name | dump }}-node-workload-dns
    name: ${{ values.name | dump }}-node-workload-dns
    title: dns
spec:
    owner: user:guest
    system: ${{ values.name | dump }}
    type: dns
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
    description: ${{ values.name | dump }}-node-workload-postgres
    name: ${{ values.name | dump }}-node-workload-postgres
    title: postgres
spec:
    owner: user:guest
    system: ${{ values.name | dump }}
    type: postgres
