apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: nodejs-service-template
  title: NodeJS Service + PostgreSQL Template
  description: An example template that creates a simple NodeJS service talking to a PostgreSQL database
  tags:
    - score
    - humanitec
    - postgres
spec:
  owner: user:guest
  type: service

  parameters:
    - title: New NodeJS Service
      required:
        - componentName
      properties:
        componentName:
          title: Component Name
          type: string
          description: Unique name of the project
          ui:autofocus: true
          ui:options:
            rows: 5
          ui:field: ValidateHumanitecAppID

  steps:
    - name: Read Environment
      id: environment
      action: humanitec:get-environment

    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.componentName }}
          image: ${{ parameters.componentName }}
          orgId: ${{ steps.environment.output.orgId }}
          cloudProvider: ${{ steps.environment.output.cloudProvider }}
          githubOrgId: ${{ steps.environment.output.githubOrgId }}

    - id: trigger-pipeline
      name: Onboard Humanitec App
      action: github:actions:dispatch
      input:
        repoUrl: 'github.com?repo=backstage&owner=${{ steps.environment.output.githubOrgId }}'
        workflowId: 'onboard-humanitec-app.yaml'
        branchOrTagName: 'main'
        workflowInputs:
          app_id: ${{ parameters.componentName }}

    - id: create-repo
      name: Create GitHub repository
      action: publish:github
      input:
        allowedHosts: ['github.com']
        defaultBranch: main
        description: This is ${{ parameters.componentName }}
        repoUrl: github.com?owner=${{ steps.environment.output.githubOrgId }}&repo=${{ parameters.componentName }}
        repoVisibility: public
        protectDefaultBranch: false
        oidcCustomization: ${{ steps.environment.output.githubOIDCCustomization }}

    - id: register
      name: Register Component in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['create-repo'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps['create-repo'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
