name: ci
permissions:
  contents: read
on:
  pull_request:
  push:
    branches: 'main'
jobs:
  test-node-service:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install score-compose
        uses: score-spec/setup-score@v3
        with:
          file: score-compose
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
      - name: make compose-test
        run: |
          cd node-service
          make compose-test
  test-podinfo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install score-compose
        uses: score-spec/setup-score@v3
        with:
          file: score-compose
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
      - name: make compose-test
        run: |
          cd podinfo
          make compose-test