name: ci
permissions:
  contents: read
on:
  pull_request:
  push:
    branches: 'main'
jobs:
  containers:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: docker build podinfo
        run: |
          docker image build -t podinfo:latest podinfo/content/
      - name: docker build node-service
        run: |
          docker image build -t node-service:latest node-service/content/
  validate-score:
    runs-on: ubuntu-latest
    env:
      HUMCTL_VERSION: '*'
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - uses: humanitec/setup-cli-action@v1
        with:
          version: ${{ env.HUMCTL_VERSION }}
      - name: humctl score validate - node-service
        run: |
          humctl score validate --local --strict node-service/content/score.yaml
      - name: humctl score validate - podinfo
        run: |
          humctl score validate --local --strict podinfo/content/score.yaml